### ISSUE TITLE
Error when using a nested activity

### ISSUE THREAD

**Issue by PestiB9** [wiyarmir/React-Native-Android-component-example#1]
I have an activity (let's call it "VideoActivity") that "extends AppCompatActivity", and i can't change it to "ReactActivity" because this activity use a class "Camera extends DialogFragment" and the build return a TypeError if i change AppCompatActivity -> ReactActivity, same if i leave it as "AppCompatActivity".

How can i solve this issue without using a module that leave the full control of the app to the java side? Because i want to implement a react-native chat that overlay this activity.

**Comment by wiyarmir** [comment]
Hi @PestiB9, this kind of open questions are better asked in [StackOverflow](https://stackoverflow.com) where you would probably receive better and faster help.

Nevertheless, in those situations what you can do is not to extend `ReactActivity` but have the important bits here: `ReactActivityDelegate`. If you look at [the sourcecode of ReactActivity](https://github.com/facebook/react-native/blob/af2bb2089327ab4a07dc71dae31b84d2e6a089c2/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java) you can see that mostly what it does is create such delegate and pass all the lifecycle callbacks.

If you do the same thing, you should be pretty much covered. If you have further doubts please use StackOverflow, I will be happy to continue the discussion there if you provide me with a link in my Twitter account.
